// Chinese display names for ATD tendency fields.
// Source of truth for UI strings: user hand-copied in-game editor sheet "111"
// (Google Sheets). English keys stay aligned with tendencyProfiles.min.json.

export const tendencyNameCN: Record<string, string> = {
  Shot: "投篮",
  "Shot Under Basket": "篮下投篮",
  "Shot Close": "近距离投篮",
  "Shot Close Left": "左侧近距离投篮",
  "Shot Close Middle": "正面近距离投篮",
  "Shot Close Right": "右侧近距离投篮",
  "Shot Mid-Range": "中投",
  "Spot Up Shot Mid-Range": "定点中投",
  "Off-Screen Shot Mid-Range": "利用掩护中投",
  "Shot Mid Left": "左侧底角中投",
  "Shot Mid Left-Center": "左侧 45 度中投",
  "Shot Mid Center": "弧顶中投",
  "Shot Mid Right-Center": "右侧 45 度中投",
  "Shot Mid Right": "右侧底角中投",
  "Shot Three": "三分投篮",
  "Spot Up Shot Three": "定点三分",
  "Off-Screen Shot Three": "利用掩护三分投篮",
  "Shot Three Left": "左侧底角三分投篮",
  "Shot Three Left-Center": "左侧45度三分投篮",
  "Shot Three Center": "弧顶三分",
  "Shot Three Right-Center": "右侧45度投篮",
  "Shot Three Right": "右侧底角三分投篮",
  "Contested Jumper Three": "防守下三分跳投",
  "Contested Jumper Mid-Range": "防守下中投",
  "Stepback Three Point Shot": "后撤步三分跳投",
  "Stepback Jumper Mid-Range": "后撤步中投",
  "Spin Jumper": "转身跳投",
  "Use Glass": "打板投篮",
  "Transition Pull-Up Three Point Shot": "攻防转换急停三分",
  "Drive Pull-Up Three": "切入急停三分",
  "Drive Pull-Up Mid-Range": "切入急停中投",
  "Step Through Shot": "跨步跳投",
  "Driving Layup": "切入上篮",
  "Spin Layup": "转身上篮",
  "Euro Step Layup": "欧洲步上篮",
  "Hop Step Layup": "跳步上篮",
  Floater: "抛投",
  "Standing Dunk": "原地扣篮",
  "Driving Dunk": "切入扣篮",
  "Flashy Dunk": "花式扣篮",
  "Alley-Oop": "空中接力",
  Putback: "补篮",
  Crash: "冲抢进攻篮板",
  Drive: "切入",
  "Spot Up Drive": "切入定点投",
  "Off-Screen Drive": "利用掩护切入",
  "Drive Right": "右侧切入",
  "Triple Threat Pump Fake": "三威胁投篮假动作",
  "Triple Threat Jab Step": "三威胁试探步",
  "Triple Threat Idle": "三威胁闲置",
  "Triple Threat Shoot": "三威胁投篮",
  "Setup With Sizeup": "花式运球调整",
  "Setup With Hesitation": "迟疑步调整",
  "No Setup Dribble": "无调整运球",
  "Driving Crossover": "变相切入",
  "Driving Double Crossover": "二次变相切入",
  "Driving Spin": "转身切入",
  "Driving Half Spin": "半转身切入",
  "Driving Stepback": "后撤步切入",
  "Driving Behind the Back": "背后运球切入",
  "Driving Dribble Hesitation": "迟疑步切入",
  "Driving In & Out": "内切外带",
  "No Driving Dribble Move": "无切入运球动作",
  "Attack Strong on Drive": "强力切入进攻",
  "Dish to Open Man": "传球到空位",
  Touches: "球感",
  "Roll vs Pop": "内切对外弹",
  "Transition Spot Up vs Cut to the Basket": "进攻转换跳投对冲框",
  "Iso vs Elite Defender": "单挑精英防守球员",
  "Iso vs Good Defender": "单挑较强防守球员",
  "Iso vs Average Defender": "单挑普通防守球员",
  "Play Discipline": "球员纪律",
  "Post Up": "背身单打",
  "Post Back Down": "背身推进",
  "Post Aggressive Backdown": "强力背身单打",
  "Post Face Up": "禁区面框进攻",
  "Post Spin": "背篮转身",
  "Post Drive": "背身切入",
  "Post Drop Step": "背身沉底步",
  "Post Hop Step": "背身跳步",
  "Shoot From Post": "禁区投篮",
  "Post Hook Left": "背身左勾手",
  "Post Hook Right": "背身右勾手",
  "Post Fade Left": "左侧背身后仰跳投",
  "Post Fade Right": "右侧背身后仰跳投",
  "Post Shimmy Shot": "背身晃肩投篮",
  "Post Stepback Shot": "背身后撤步跳投",
  "Post Up & Under": "背身上下步",
  "Flashy Pass": "花式传球",
  "Alley-Oop Pass": "空中接力传球",
  "Take Charge": "制造进攻犯规",
  Foul: "犯规",
  "Pass Interception": "干扰传球",
  "On-Ball Steal": "持球抢断",
  "Block Shot": "盖帽",
  "Hard Foul": "强硬犯规",
};

/** In-game UI terms that are not present in the ATD 96-field table. */
export const tendencyNameCNExtraUI: Record<string, string> = {
  "Iso vs Poor Defender": "单挑较弱防守球员",
  ContestShot: "干扰投篮",
  PostHopStepShot: "背身跳步投篮",
};

export function getTendencyNameCN(field: string): string {
  return tendencyNameCN[field] ?? field;
}
